// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using example_db.Data;

#nullable disable

namespace exemploapi.Migrations
{
    [DbContext(typeof(MyProjectDbContext))]
    [Migration("20240605202201_bu")]
    partial class bu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("exemploapi.MVC.model.Anime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("eh_dublado")
                        .HasColumnType("bit");

                    b.Property<bool?>("eh_legendado")
                        .HasColumnType("bit");

                    b.Property<string>("link_capa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sinopse")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Anime");
                });

            modelBuilder.Entity("exemploapi.MVC.model.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ComentarioId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("animeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("data_insercao")
                        .HasColumnType("datetime2");

                    b.Property<string>("link_capa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("link_src")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("n_episodio")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sinopse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("views")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComentarioId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("animeId");

                    b.ToTable("Comentario");
                });

            modelBuilder.Entity("exemploapi.MVC.model.Episodio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("episodioId")
                        .HasColumnType("int");

                    b.Property<int?>("usuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("episodioId");

                    b.HasIndex("usuarioId");

                    b.ToTable("Episodio");
                });

            modelBuilder.Entity("exemploapi.MVC.model.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("eh_admin")
                        .HasColumnType("bit");

                    b.Property<string>("link_foto_perfil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("senha")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("exemploapi.MVC.model.Usuario_Episodio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ComentarioId")
                        .HasColumnType("int");

                    b.Property<int>("episodioId")
                        .HasColumnType("int");

                    b.Property<string>("texto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("usuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComentarioId");

                    b.HasIndex("episodioId");

                    b.HasIndex("usuarioId");

                    b.ToTable("Usuario_Episodio");
                });

            modelBuilder.Entity("exemploapi.MVC.model.Comentario", b =>
                {
                    b.HasOne("exemploapi.MVC.model.Comentario", null)
                        .WithMany("comentarios")
                        .HasForeignKey("ComentarioId");

                    b.HasOne("exemploapi.MVC.model.Usuario", null)
                        .WithMany("comentarios")
                        .HasForeignKey("UsuarioId");

                    b.HasOne("exemploapi.MVC.model.Anime", "anime")
                        .WithMany()
                        .HasForeignKey("animeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("anime");
                });

            modelBuilder.Entity("exemploapi.MVC.model.Episodio", b =>
                {
                    b.HasOne("exemploapi.MVC.model.Episodio", "episodio")
                        .WithMany()
                        .HasForeignKey("episodioId");

                    b.HasOne("exemploapi.MVC.model.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("usuarioId");

                    b.Navigation("episodio");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("exemploapi.MVC.model.Usuario_Episodio", b =>
                {
                    b.HasOne("exemploapi.MVC.model.Comentario", null)
                        .WithMany("visualizacoes")
                        .HasForeignKey("ComentarioId");

                    b.HasOne("exemploapi.MVC.model.Episodio", "episodio")
                        .WithMany()
                        .HasForeignKey("episodioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("exemploapi.MVC.model.Usuario", "usuario")
                        .WithMany("visualizacoes")
                        .HasForeignKey("usuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("episodio");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("exemploapi.MVC.model.Comentario", b =>
                {
                    b.Navigation("comentarios");

                    b.Navigation("visualizacoes");
                });

            modelBuilder.Entity("exemploapi.MVC.model.Usuario", b =>
                {
                    b.Navigation("comentarios");

                    b.Navigation("visualizacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
